In [1]:
import tensorflow as tf
import keras
import cv2
import numpy as np
import itertools
import os
import seaborn as sns
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive


In [3]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
dir=('/content/drive/MyDrive/dataset/train1/')

In [5]:
classes=["happy1","sad1"]

read all the img and convertin them to array

In [6]:
training_data=[]
img_size=224 
def create_training_data():
  for category in classes:
    path=os.path.join(dir,category)
    class_num=classes.index(category)
    for img in os.listdir(path):
      try:
        img_array=cv2.imread(os.path.join(path,img))
        new_array=cv2.resize(img_array,(img_size,img_size))
        training_data.append([new_array, class_num])
      except Exception as e:
        pass 


In [7]:
create_training_data()

In [8]:
print(len(training_data))

1778


In [9]:
temp=np.array(training_data)

<ipython-input-9-357a9f251f7e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp=np.array(training_data)


In [10]:
temp.shape

(1778, 2)

In [11]:
import random
random.shuffle(training_data)

In [12]:
x=[] #feature/data
y=[] #label

for features,label in training_data:
  
  x.append(features)
  y.append(label)

x=np.array(x)
y=np.array(y)

In [13]:
x.shape

(1778, 224, 224, 3)

In [14]:
x=x/255.0

In [15]:
X=x.reshape(1778,3*224*224)

In [16]:
X.shape

(1778, 150528)

In [17]:
y.shape

(1778,)

In [18]:
dir1=('/content/drive/MyDrive/dataset/train')

In [19]:
classes1=["H1","sad"]

In [20]:
test_data=[]
img_size=224 
def create_test_data():
  for category in classes1:
    path=os.path.join(dir1,category)
    class_num=classes1.index(category)
    for img in os.listdir(path):
      try:
        img_array=cv2.imread(os.path.join(path,img))
        new_array=cv2.resize(img_array,(img_size,img_size))
        test_data.append([new_array, class_num])
      except Exception as e:
        pass 

In [21]:
create_test_data()

In [22]:
temp1=np.array(test_data)

<ipython-input-22-3bdf79796c9f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp1=np.array(test_data)


In [23]:
temp1.shape

(72, 2)

In [24]:
import random
random.shuffle(test_data)

In [25]:
x1=[] #feature/data
y1=[] #label

for features,label in test_data:
  
  x1.append(features)
  y1.append(label)

x1=np.array(x1)
y1=np.array(y1)

In [26]:
x1.shape

(72, 224, 224, 3)

In [27]:
a=x1.reshape(72,224*224*3)

In [28]:
a=a/255.0

In [29]:
a

array([[0.16470588, 0.16470588, 0.16470588, ..., 0.18039216, 0.18039216,
        0.18039216],
       [0.08627451, 0.08627451, 0.08627451, ..., 0.11372549, 0.11372549,
        0.11372549],
       [0.34117647, 0.34117647, 0.34117647, ..., 0.61568627, 0.61568627,
        0.61568627],
       ...,
       [0.16470588, 0.16470588, 0.16470588, ..., 0.01176471, 0.01176471,
        0.01176471],
       [0.3372549 , 0.3372549 , 0.3372549 , ..., 0.84705882, 0.84705882,
        0.84705882],
       [0.81568627, 0.81568627, 0.81568627, ..., 0.28627451, 0.28627451,
        0.28627451]])

In [30]:
X.shape

(1778, 150528)

In [31]:
y.shape

(1778,)

In [32]:
a.shape

(72, 150528)

In [33]:
import xgboost as xgb
my_model = xgb.XGBClassifier(n_estimators=1000, learning_rate=0.005, n_jobs=4)
my_model.fit(X,y, 
             early_stopping_rounds=5, 
             eval_set=[(a, y1)], 
             verbose=False)

XGBClassifier(learning_rate=0.005, n_estimators=1000, n_jobs=4)

In [34]:
predictions = my_model.predict(a)

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
predictions

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0])

In [37]:
y1

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0])

In [38]:
print(confusion_matrix(y1,predictions))

[[48  3]
 [14  7]]


In [39]:
print(classification_report(y1,predictions))

              precision    recall  f1-score   support

           0       0.77      0.94      0.85        51
           1       0.70      0.33      0.45        21

    accuracy                           0.76        72
   macro avg       0.74      0.64      0.65        72
weighted avg       0.75      0.76      0.73        72

